### ISSUE TITLE
Ubuntu 24.04 kernel 6.14.x fails to install gasket_dkms.deb build from sources

### ISSUE THREAD

**Issue by x00e** [google/gasket-driver#47]
````
❯ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.2 LTS"
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
````

````
❯ uname -r
6.14.0-24-generic
````

Following instructions to clone repo & build .deb file, I do a get .deb file, but this package fails to successfully install: 
 
````
❯ sudo dpkg -i gasket-dkms_1.0-18_all.deb
(Reading database ... 182056 files and directories currently installed.)
Preparing to unpack gasket-dkms_1.0-18_all.deb ...
Deleting module gasket-1.0 completely from the DKMS tree.
Unpacking gasket-dkms (1.0-18) over (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
locale: Cannot set LC_ALL to default locale: No such file or directory
Loading new gasket-1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.14.0-24-generic
Building initial module for 6.14.0-24-generic
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/gasket-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.14.0-24-generic (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--install):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
````

````
❯ cat  /var/lib/dkms/gasket/1.0/build/make.log
DKMS make.log for gasket-1.0 for kernel 6.14.0-24-generic (x86_64)
Fri Jul 18 11:38:24 AM UTC 2025
make: Entering directory '/usr/src/linux-headers-6.14.0-24-generic'
make[1]: Entering directory '/var/lib/dkms/gasket/1.0/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  gasket_core.o
  CC [M]  gasket_ioctl.o
  CC [M]  gasket_interrupt.o
  CC [M]  gasket_page_table.o
gasket_core.c:1376:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
 1376 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
In file included from /usr/src/linux-headers-6.14.0-24-generic/include/linux/module.h:22,
                 from /usr/src/linux-headers-6.14.0-24-generic/include/linux/device/driver.h:21,
                 from /usr/src/linux-headers-6.14.0-24-generic/include/linux/device.h:32,
                 from /usr/src/linux-headers-6.14.0-24-generic/include/linux/pci.h:37,
                 from gasket_page_table.h:15,
                 from gasket_page_table.c:42:
gasket_page_table.c:57:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
/usr/src/linux-headers-6.14.0-24-generic/include/linux/moduleparam.h:26:61: note: in definition of macro ‘__MODULE_INFO’
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/usr/src/linux-headers-6.14.0-24-generic/include/linux/module.h:301:33: note: in expansion of macro ‘MODULE_INFO’
  301 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
gasket_page_table.c:57:1: note: in expansion of macro ‘MODULE_IMPORT_NS’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.14.0-24-generic/scripts/Makefile.build:207: gasket_core.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-headers-6.14.0-24-generic/scripts/Makefile.build:207: gasket_page_table.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.14.0-24-generic/Makefile:2002: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.14.0-24-generic/Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/gasket/1.0/build'
make: *** [Makefile:251: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.14.0-24-generic'

````

[gasket-dkms_1.0-18_amd64.build.txt](https://github.com/user-attachments/files/21315581/gasket-dkms_1.0-18_amd64.build.txt)
[gasket-dkms_1.0-18_amd64.buildinfo.txt](https://github.com/user-attachments/files/21315582/gasket-dkms_1.0-18_amd64.buildinfo.txt)
[gasket-dkms_1.0-18_amd64.changes.txt](https://github.com/user-attachments/files/21315583/gasket-dkms_1.0-18_amd64.changes.txt)

**Comment by sethyx** [comment]
Feel free to use my fork, Google does not seem to be monitoring this unfortunately.
Tested on Ubuntu 24.04 with 6.14 HWE kernel: https://github.com/sethyx/gasket-driver

**Comment by x00e** [comment]
> Feel free to use my fork, Google does not seem to be monitoring this unfortunately. Tested on Ubuntu 24.04 with 6.14 HWE kernel: https://github.com/sethyx/gasket-driver

Thanks mate, that did the trick!
