### ISSUE TITLE
Unable to update/build DKMS on Debian 13 (Trixie) from Coral apt repo

### ISSUE THREAD

**Issue by Drizzt321** [google/gasket-driver#56]
I've had a system with Debian 12 running my Dual M.2 Cora TPUs just fine for quite a while, upgraded it to Trixie (Debian 13), and having an issue with the DKMS driver. 

The instructions from https://www.coral.ai/docs/edgetpu/compiler#download were used to install it originally, I found that I had to use [these instructions](https://www.reddit.com/r/frigate_nvr/comments/1hr48o3/comment/mstbi70/) to get the key updated properly for the new Sources format. So those instructions need updating (not sure if this repo actually is responsible for that).

During update of the kernel to 6.12.57, I'm getting the following error when trying to build gasket-dkms

```
Setting up gasket-dkms (1.0-18) ...
Removing old gasket/1.0 DKMS files...
Deleting module gasket/1.0 completely from the DKMS tree.
Loading new gasket/1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.12.57+deb13-amd64

Building initial module gasket/1.0 for 6.12.57+deb13-amd64
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
Sign command: /lib/modules/6.12.57+deb13-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j3 KERNELRELEASE=6.12.57+deb13-amd64 -C /lib/modules/6.12.57+deb13-amd64/build M=/var/lib/dkms/gasket/1.0/build

Error! Bad return status for module build on kernel: 6.12.57+deb13-amd64 (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
Error: Sub-process /usr/bin/dpkg returned an error code (1)
```

The referenced log file output is this:
```
DKMS (dkms-3.2.2) make.log for gasket/1.0 for kernel 6.12.57+deb13-amd64 (x86_64)
Tue Dec 23 12:38:29 PM PST 2025

Building module(s)
# command: make -j3 KERNELRELEASE=6.12.57+deb13-amd64 -C /lib/modules/6.12.57+deb13-amd64/build M=/var/lib/dkms/gasket/1.0/build
make: Entering directory '/usr/src/linux-headers-6.12.57+deb13-amd64'
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:161:17: error: too many arguments to function ‘eventfd_signal’
  161 |                 eventfd_signal(ctx, 1);
      |                 ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:4:
/usr/src/linux-headers-6.12.57+deb13-common/include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1375:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
 1375 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
/var/lib/dkms/gasket/1.0/build/gasket_core.c: In function ‘gasket_register_device’:
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Wincompatible-pointer-types]
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                              ~~~~~~~~~~~^~~~~~~~
      |                                         |
      |                                         struct module *
In file included from /usr/src/linux-headers-6.12.57+deb13-common/include/linux/device.h:30,
                 from /usr/src/linux-headers-6.12.57+deb13-common/include/linux/cdev.h:8,
                 from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
/usr/src/linux-headers-6.12.57+deb13-common/include/linux/device/class.h:228:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  228 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                 ^~~~~~~~~~~~
/usr/src/linux-headers-6.12.57+deb13-common/include/linux/device/class.h:228:29: note: declared here
  228 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
make[2]: *** [/usr/src/linux-headers-6.12.57+deb13-common/scripts/Makefile.build:234: /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-6.12.57+deb13-common/scripts/Makefile.build:234: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.12.57+deb13-common/Makefile:1970: /var/lib/dkms/gasket/1.0/build] Error 2
make: *** [/usr/src/linux-headers-6.12.57+deb13-common/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.57+deb13-amd64'

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```
