### ISSUE TITLE
fails to compile on Ubuntu's latest 6.8.x

### ISSUE THREAD

**Issue by derekcentrico** [google/gasket-driver#30]
> DKMS make.log for gasket-1.0 for kernel 6.8.0-40-generic (x86_64)
> Sun Aug 25 08:18:37 PM EDT 2024
> make: Entering directory '/usr/src/linux-headers-6.8.0-40-generic'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>   You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
>   CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
> /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
> /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:161:17: error: too many arguments to function ‘eventfd_signal’
>   161 |                 eventfd_signal(ctx, 1);
>       |                 ^~~~~~~~~~~~~~
> In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.h:11,
>                  from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:4:
> ./include/linux/eventfd.h:87:20: note: declared here
>    87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
>       |                    ^~~~~~~~~~~~~~
> make[2]: *** [scripts/Makefile.build:243: /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [/usr/src/linux-headers-6.8.0-40-generic/Makefile:1926: /var/lib/dkms/gasket/1.0/build] Error 2
> make: *** [Makefile:240: __sub-make] Error 2
> make: Leaving directory '/usr/src/linux-headers-6.8.0-40-generic'

Worked for kernels 5.15 - 6.6.  First 6.8 from Ubuntu and negative.

**Comment by derekcentrico** [comment]
Apparently my local repo didn't match the April change?  Worked after deleting and redownloading.  Weird.
