### ISSUE TITLE
debuild succuessful but dpkg fails

### ISSUE THREAD

**Issue by tvrulesme** [google/gasket-driver#53]
Followed all the instructions here:
https://github.com/google-coral/edgetpu/issues/866#issuecomment-2417201658

debuild was succuessful
```
debuild -us -uc -tc -b -d
 dpkg-buildpackage -us -uc -ui -tc -b -d
dpkg-buildpackage: info: source package gasket-dkms
dpkg-buildpackage: info: source version 1.0-18
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Coral <coral-support@google.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with dkms
   dh_clean
 debian/rules build
dh build --with dkms
   dh_update_autotools_config
   dh_autoreconf
   create-stamp debian/debhelper-build-stamp
 fakeroot debian/rules binary
dh binary --with dkms
   dh_testroot
   dh_prep
   debian/rules override_dh_install
make[1]: Entering directory '/home/tvrulesme/docker/gasket-driver'
dh_install src/* usr/src/gasket-1.0/
make[1]: Leaving directory '/home/tvrulesme/docker/gasket-driver'
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_dkms
make[1]: Entering directory '/home/tvrulesme/docker/gasket-driver'
dh_dkms -V 1.0
make[1]: Leaving directory '/home/tvrulesme/docker/gasket-driver'
   dh_installudev
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'gasket-dkms' in '../gasket-dkms_1.0-18_all.deb'.
 dpkg-genbuildinfo --build=binary -O../gasket-dkms_1.0-18_amd64.buildinfo
 dpkg-genchanges --build=binary -O../gasket-dkms_1.0-18_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 fakeroot debian/rules clean
dh clean --with dkms
   dh_clean
 dpkg-source --after-build .
dpkg-buildpackage: info: binary-only upload (no source included)
Now running lintian gasket-dkms_1.0-18_amd64.changes ...
E: gasket-dkms changes: bad-distribution-in-changes-file unstable
Finished running lintian.
```

sudo dpkg -i ../gasket-dkms_1.0-18_all.deb fails

```
ERROR (dkms apport): kernel package linux-headers-6.16.7-061607-generic is not supported
Error! Bad return status for module build on kernel: 6.16.7-061607-generic (x86_64)
```

Tried everything and I just can't get it to play ball

**Comment by tvrulesme** [comment]
Little bit more of what I have tried based on this
https://github.com/google-coral/edgetpu/issues/220#issuecomment-692766793

```
tollgate-server:/usr/src$ ls -lat
total 56
drwxr-xr-x  2 root root 4096 Sep 13 11:40 gasket-1.0
drwxr-xr-x 14 root root 4096 Sep 13 11:40 .
drwxr-xr-x  3 root root 4096 Sep 13 11:11 gasket-dkms-1.0
drwxr-xr-x  7 root root 4096 Sep 13 10:55 linux-headers-6.8.0-79-generic
drwxr-xr-x 26 root root 4096 Sep 13 10:54 linux-headers-6.8.0-79
drwxr-xr-x 25 root root 4096 Sep 13 09:03 linux-headers-6.16.7-061607
drwxr-xr-x  7 root root 4096 Sep 13 09:03 linux-headers-6.16.7-061607-generic
drwxr-xr-x  7 root root 4096 Aug 30 06:51 linux-headers-6.14.0-29-generic
drwxr-xr-x 26 root root 4096 Aug 30 06:50 linux-hwe-6.14-headers-6.14.0-29
drwxr-xr-x  7 root root 4096 Jul  2 06:28 linux-headers-6.11.0-29-generic
drwxr-xr-x 26 root root 4096 Jul  2 06:28 linux-hwe-6.11-headers-6.11.0-29
drwxr-xr-x  7 root root 4096 May 21 06:01 linux-headers-6.11.0-26-generic
drwxr-xr-x 26 root root 4096 May 21 06:01 linux-hwe-6.11-headers-6.11.0-26
```

```
sudo dkms build gasket-dkms/1.0 --kernelsourcedir=/usr/src/linux-headers-$(uname -r)
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket-dkms/1.0/source/dkms.conf)

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.16.7-061607-generic -C /usr/src/linux-headers-6.16.7-061607-generic M=/var/lib/dkms/gasket-dkms/1.0/build.....(bad exit status: 2)
ERROR (dkms apport): binary package for gasket-dkms: 1.0 not found
Error! Bad return status for module build on kernel: 6.16.7-061607-generic (x86_64)
Consult /var/lib/dkms/gasket-dkms/1.0/build/make.log for more information.
```

```
KMS make.log for gasket-dkms-1.0 for kernel 6.16.7-061607-generic (x86_64)
Sat Sep 13 01:15:58 PM BST 2025
make: Entering directory '/usr/src/linux-headers-6.16.7-061607-generic'
make[1]: Entering directory '/var/lib/dkms/gasket-dkms/1.0/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-14 (Ubuntu 14.2.0-23ubuntu1) 14.2.0
  You are using:           gcc-14 (Ubuntu 14.2.0-4ubuntu2~24.04) 14.2.0
  CC [M]  gasket_core.o
  CC [M]  gasket_ioctl.o
  CC [M]  gasket_interrupt.o
  CC [M]  gasket_page_table.o
gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
gasket_interrupt.c:161:17: error: too many arguments to function ‘eventfd_signal’
  161 |                 eventfd_signal(ctx, 1);
      |                 ^~~~~~~~~~~~~~
In file included from gasket_interrupt.h:11,
                 from gasket_interrupt.c:4:
```

**Comment by tvrulesme** [comment]
More investigation. I think it's to do with the availability of linux headers

```
uname -r
6.16.7-061607-generic
```
Which means that gasket-driver is looking for linux-headers-6.16.7-061607-generic but the latest version is linux-headers-6.8.0-79-generic
```
dpkg-query -s linux-headers-generic
Package: linux-headers-generic
Status: install ok installed
Priority: optional
Section: kernel
Installed-Size: 17
Maintainer: Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>
Architecture: amd64
Source: linux-meta
Version: 6.8.0-79.79
Depends: linux-headers-6.8.0-79-generic
Description: Generic Linux kernel headers
 This package will always depend on the latest generic kernel headers
 available.
```
