### ISSUE TITLE
Fail to compile in linux kernel 4.19.294

### ISSUE THREAD

**Issue by PinxuanHuang** [google/gasket-driver#34]
Currently I put this driver module under the kernel driver staging folder and compile the kernel and I've encountered this compile error. 

I wonder know that whether this driver is compatible with linux kernel 4.19.294 (my kernel version) and may I compile this driver by myself without using dkms to install it ?

```
drivers/staging/gasket/gasket_page_table.c:57:1: warning: data definition has no type or storage class
   57 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
drivers/staging/gasket/gasket_page_table.c:57:1: error: type defaults to ‘int’ in declaration of ‘MODULE_IMPORT_NS’ [-Werror=implicit-int]
drivers/staging/gasket/gasket_page_table.c:57:1: warning: parameter names (without types) in function declaration
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/staging/gasket/gasket_page_table.o' failed
```
 
- kernel version 
  - 4.19.294

- gasket-driver version
  - the latest commit version
